### ISSUE TITLE
xxxFields Classes Not Always Generated

### ISSUE THREAD

**Issue by ghost** [cmelchior/realmfieldnameshelper#10] opened 2016-11-11 04:38 UTC
I've been using your library to great success. However, it seems to have randomly stopped generating the Fields classes. 

Gradle version: 2.2.0
Realm version: 2.1.1
Gradle tasks used: clean build, clean assembleDebug

**Comment by Zhuinden** [comment] 2016-12-09 13:32
do you use android-apt?

What is your plugin apply order in build gradle?

**Comment by cmelchior** [comment] 2017-02-21 23:54
Closing this since it cannot be reproduced.

**Closed as completed by cmelchior** 2017-02-21 23:54 UTC
Labels: question
